=== SaPeLia/LaVuelta2026_SEW/xml/etapa.dtd
<!ELEMENT etapa (
    nombre,
    número,
    longitud,
    fecha,
    tiempoGanador,
    velocidadMedia,
    desnivel,
    ciudadSalida,
    ciudadLlegada,
    tipo,
    referencias,
    multimedia,
    hitos,
    puntosAnónimos,
    clasificaciónEtapa,
    clasificaciónGeneral,
    clasificaciónEquipos
)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT número (#PCDATA)>
<!ELEMENT longitud (#PCDATA)>
<!ATTLIST longitud unidad CDATA #REQUIRED
>

<!ELEMENT fecha (#PCDATA)>
<!ELEMENT tiempoGanador (#PCDATA)>

<!ELEMENT velocidadMedia (#PCDATA)>
<!ATTLIST velocidadMedia unidad CDATA #REQUIRED
>

<!ELEMENT desnivel (#PCDATA)>
<!ATTLIST desnivel unidad CDATA #REQUIRED
>


<!-- CIUDADES -->

<!ELEMENT ciudadSalida (puntoGeografico)>
<!ATTLIST ciudadSalida nombre CDATA #REQUIRED
>

<!ELEMENT ciudadLlegada (puntoGeografico)>
<!ATTLIST ciudadLlegada nombre CDATA #REQUIRED
>

<!ELEMENT puntoGeografico (
    longitud,
    latitud,
    altitud
)>

<!ELEMENT latitud (#PCDATA)>
<!ATTLIST latitud unidad CDATA #REQUIRED
>

<!ELEMENT altitud (#PCDATA)>
<!ATTLIST altitud unidad CDATA #REQUIRED
>


<!-- REFERENCIAS -->

<!ELEMENT referencias (referencia+)>

<!ELEMENT referencia EMPTY>
<!ATTLIST referencia
    título CDATA #REQUIRED
    url CDATA #REQUIRED
>


<!-- MULTIMEDIA -->

<!ELEMENT multimedia (
    fotografías+,
    vídeos+,
    audios+
)>

<!ELEMENT fotografías (fotografía+)>

<!ELEMENT fotografía EMPTY>
<!ATTLIST fotografía descripción CDATA #REQUIRED
    archivo CDATA #REQUIRED
>

<!ELEMENT vídeos (vídeo+)>

<!ELEMENT vídeo EMPTY>
<!ATTLIST vídeo descripción CDATA #REQUIRED
    archivo CDATA #REQUIRED
>

<!ELEMENT audios (audio+)>

<!ELEMENT audio EMPTY>
<!ATTLIST audio
    descripción CDATA #REQUIRED
    archivo CDATA #REQUIRED
>


<!-- HITOS -->

<!ELEMENT hitos (hito+)>

<!ELEMENT hito (
    (puerto | sprint),
    distanciaDesdeSalida,
    puntoGeografico
)>

<!ELEMENT puerto EMPTY>
<!ATTLIST puerto
    tipo CDATA #REQUIRED
    nombre CDATA #REQUIRED
>

<!ELEMENT sprint EMPTY>
<!ATTLIST sprint
    tipo CDATA #REQUIRED
>

<!ELEMENT distanciaDesdeSalida (#PCDATA)>
<!ATTLIST distanciaDesdeSalida unidad CDATA #REQUIRED
>


<!-- PUNTOS ANÓNIMOS -->

<!ELEMENT puntosAnónimos (puntoAnónimo+)>

<!ELEMENT puntoAnónimo (
    distanciaDesdeSalida,
    puntoGeografico
)>

<!ATTLIST puntoAnónimo nombre CDATA #REQUIRED
>


<!-- CLASIFICACIÓN DE LA ETAPA -->

<!ELEMENT clasificaciónEtapa (clasificado+)>

<!ELEMENT clasificado (
    corredor,
    nombreEquipo,
    tiempo,
    diferencia
)>

<!ATTLIST clasificado posición CDATA #REQUIRED
>

<!ELEMENT corredor (#PCDATA)>
<!ELEMENT nombreEquipo (#PCDATA)>
<!ELEMENT tiempo (#PCDATA)>
<!ELEMENT diferencia (#PCDATA)>


<!-- CLASIFICACIÓN GENERAL -->

<!ELEMENT clasificaciónGeneral (clasificado+)>


<!-- CLASIFICACIÓN DE EQUIPOS -->

<!ELEMENT clasificaciónEquipos (equipoClasificación+)>

<!ELEMENT equipoClasificación (
    nombre,
    diferencia
)>

<!ATTLIST equipoClasificación posición CDATA #REQUIRED
>

=== SaPeLia/LaVuelta2026_SEW/xml/etapa.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE etapa SYSTEM "etapa.dtd">
<etapa>
<nombre>Jaén a Sierra de la Pandera</nombre>
<número>14</número>
<longitud unidad="km">154.5</longitud>
<fecha>05/09/2026</fecha>
<tiempoGanador>04:15:09</tiempoGanador>
<velocidadMedia unidad="km/h">22</velocidadMedia>
<desnivel unidad="m">100</desnivel>
<ciudadSalida nombre="Jaén">
    <puntoGeografico>
        <longitud unidad="grados">-3.7849</longitud>
        <latitud unidad="grados">37.7796</latitud>
        <altitud unidad="m">573</altitud>
    </puntoGeografico>
</ciudadSalida>

<ciudadLlegada nombre="Sierra de la Pandera">
    <puntoGeografico>
        <longitud unidad="grados">-3.8049</longitud>
        <latitud unidad="grados">37.6888</latitud>
        <altitud unidad="m">1830</altitud>
    </puntoGeografico>
</ciudadLlegada>
<tipo>montaña</tipo>
<referencias>
    <referencia título="1" url="..."></referencia>
    <referencia título="2" url="..."></referencia>
    <referencia título="3" url="..."></referencia>
</referencias>
<multimedia>
    <fotografías>
        <fotografía descripción="foto1" archivo="../multimedia/foto1.jpg"></fotografía>
        <fotografía descripción="foto2" archivo="../multimedia/foto2.jpg"></fotografía>
        <fotografía descripción="foto3" archivo="../multimedia/foto3.jpg"></fotografía>
    </fotografías>
    <vídeos>
        <vídeo descripción="vídeo1" archivo="../multimedia/vídeo1.mp4"></vídeo>
    </vídeos>
    <audios>
        <audio descripción="audio1" archivo="../multimedia/audio1.mp3"></audio>
    </audios>
</multimedia>

<hitos>
    <!-- Puerto de Los Villares: km 82,3 -->
    <hito>
        <puerto nombre="Puerto de Los Villares" tipo="2ª Categoría" />
        <distanciaDesdeSalida unidad="km">82.3</distanciaDesdeSalida>
        <puntoGeografico>
            <longitud unidad="grados">-3.8150</longitud>
            <latitud unidad="grados">37.6860</latitud>
            <altitud unidad="m">1250</altitud>
        </puntoGeografico>
    </hito>

    <!-- Sprint intermedio: km 123,6 -->
    <hito>
        <sprint tipo="intermedio" />
        <distanciaDesdeSalida unidad="km">123.6</distanciaDesdeSalida>
        <puntoGeografico>
            <longitud unidad="grados">-3.6440</longitud>
            <latitud unidad="grados">37.5790</latitud>
            <altitud unidad="m">950</altitud>
        </puntoGeografico>
    </hito>

    <!-- Puerto de Locubín: km 133,2 -->
    <hito>
        <puerto nombre="Puerto de Locubín" tipo="2ª Categoría" />
        <distanciaDesdeSalida unidad="km">133.2</distanciaDesdeSalida>
        <puntoGeografico>
            <longitud unidad="grados">-3.8150</longitud>
            <latitud unidad="grados">37.5700</latitud>
            <altitud unidad="m">1200</altitud>
        </puntoGeografico>
    </hito>

    <!-- Ascensión final -->
    <hito>
        <puerto nombre="Sierra de la Pandera" tipo="1ª Categoría" />
        <distanciaDesdeSalida unidad="km">154.5</distanciaDesdeSalida>
        <puntoGeografico>
            <longitud unidad="grados">-3.8049</longitud>
            <latitud unidad="grados">37.6888</latitud>
            <altitud unidad="m">1830</altitud>
        </puntoGeografico>
    </hito>
</hitos>

<puntosAnónimos>
    <puntoAnónimo nombre="Salida de Jaén">
        <distanciaDesdeSalida unidad="km">0.0</distanciaDesdeSalida>
        <puntoGeografico>
            <longitud unidad="grados">-3.7849</longitud>
            <latitud unidad="grados">37.7796</latitud>
            <altitud unidad="m">573</altitud>
        </puntoGeografico>
    </puntoAnónimo>

    <puntoAnónimo nombre="Rotonda dirección Mancha Real">
        <distanciaDesdeSalida unidad="km">3.4</distanciaDesdeSalida>
        <puntoGeografico>
            <longitud unidad="grados">-3.7800</longitud>
            <latitud unidad="grados">37.7900</latitud>
            <altitud unidad="m">580</altitud>
        </puntoGeografico>
    </puntoAnónimo>

    <puntoAnónimo nombre="Cruce dirección Mancha Real">
        <distanciaDesdeSalida unidad="km">9.1</distanciaDesdeSalida>
        <puntoGeografico>
            <longitud unidad="grados">-3.7700</longitud>
            <latitud unidad="grados">37.8000</latitud>
            <altitud unidad="m">610</altitud>
        </puntoGeografico>
    </puntoAnónimo>

    <puntoAnónimo nombre="Mancha Real">
        <distanciaDesdeSalida unidad="km">13.5</distanciaDesdeSalida>
        <puntoGeografico>
            <longitud unidad="grados">-3.6120</longitud>
            <latitud unidad="grados">37.7860</latitud>
            <altitud unidad="m">750</altitud>
        </puntoGeografico>
    </puntoAnónimo>

    <puntoAnónimo nombre="Cruce dirección Torres">
        <distanciaDesdeSalida unidad="km">24.6</distanciaDesdeSalida>
        <puntoGeografico>
            <longitud unidad="grados">-3.6500</longitud>
            <latitud unidad="grados">37.7500</latitud>
            <altitud unidad="m">850</altitud>
        </puntoGeografico>
    </puntoAnónimo>

    <puntoAnónimo nombre="Torres">
        <distanciaDesdeSalida unidad="km">33.1</distanciaDesdeSalida>
        <puntoGeografico>
            <longitud unidad="grados">-3.5100</longitud>
            <latitud unidad="grados">37.7850</latitud>
            <altitud unidad="m">880</altitud>
        </puntoGeografico>
    </puntoAnónimo>

    <puntoAnónimo nombre="Pegalajar">
        <distanciaDesdeSalida unidad="km">52.9</distanciaDesdeSalida>
        <puntoGeografico>
            <longitud unidad="grados">-3.6500</longitud>
            <latitud unidad="grados">37.7400</latitud>
            <altitud unidad="m">800</altitud>
        </puntoGeografico>
    </puntoAnónimo>

    <puntoAnónimo nombre="Rotonda dirección Jaén">
        <distanciaDesdeSalida unidad="km">57.9</distanciaDesdeSalida>
        <puntoGeografico>
            <longitud unidad="grados">-3.7200</longitud>
            <latitud unidad="grados">37.7500</latitud>
            <altitud unidad="m">700</altitud>
        </puntoGeografico>
    </puntoAnónimo>

    <puntoAnónimo nombre="La Guardia de Jaén">
        <distanciaDesdeSalida unidad="km">61.2</distanciaDesdeSalida>
        <puntoGeografico>
            <longitud unidad="grados">-3.6900</longitud>
            <latitud unidad="grados">37.7450</latitud>
            <altitud unidad="m">600</altitud>
        </puntoGeografico>
    </puntoAnónimo>

    <puntoAnónimo nombre="Puente Jontoya">
        <distanciaDesdeSalida unidad="km">67.2</distanciaDesdeSalida>
        <puntoGeografico>
            <longitud unidad="grados">-3.7700</longitud>
            <latitud unidad="grados">37.7350</latitud>
            <altitud unidad="m">550</altitud>
        </puntoGeografico>
    </puntoAnónimo>

    <puntoAnónimo nombre="Los Villares">
        <distanciaDesdeSalida unidad="km">82.3</distanciaDesdeSalida>
        <puntoGeografico>
            <longitud unidad="grados">-3.8150</longitud>
            <latitud unidad="grados">37.6860</latitud>
            <altitud unidad="m">980</altitud>
        </puntoGeografico>
    </puntoAnónimo>

    <puntoAnónimo nombre="Fuensanta de Martos">
        <distanciaDesdeSalida unidad="km">101.2</distanciaDesdeSalida>
        <puntoGeografico>
            <longitud unidad="grados">-3.9050</longitud>
            <latitud unidad="grados">37.6470</latitud>
            <altitud unidad="m">720</altitud>
        </puntoGeografico>
    </puntoAnónimo>

    <puntoAnónimo nombre="El Regüelo">
        <distanciaDesdeSalida unidad="km">109.3</distanciaDesdeSalida>
        <puntoGeografico>
            <longitud unidad="grados">-3.8900</longitud>
            <latitud unidad="grados">37.6100</latitud>
            <altitud unidad="m">800</altitud>
        </puntoGeografico>
    </puntoAnónimo>

    <puntoAnónimo nombre="Castillo de Locubín">
        <distanciaDesdeSalida unidad="km">123.1</distanciaDesdeSalida>
        <puntoGeografico>
            <longitud unidad="grados">-3.9430</longitud>
            <latitud unidad="grados">37.5280</latitud>
            <altitud unidad="m">700</altitud>
        </puntoGeografico>
    </puntoAnónimo>

    <puntoAnónimo nombre="Comienzo del puerto final">
        <distanciaDesdeSalida unidad="km">124.4</distanciaDesdeSalida>
        <puntoGeografico>
            <longitud unidad="grados">-3.9000</longitud>
            <latitud unidad="grados">37.5600</latitud>
            <altitud unidad="m">850</altitud>
        </puntoGeografico>
    </puntoAnónimo>

    <puntoAnónimo nombre="Valdepeñas de Jaén">
        <distanciaDesdeSalida unidad="km">139.5</distanciaDesdeSalida>
        <puntoGeografico>
            <longitud unidad="grados">-3.8150</longitud>
            <latitud unidad="grados">37.5870</latitud>
            <altitud unidad="m">920</altitud>
        </puntoGeografico>
    </puntoAnónimo>

    <puntoAnónimo nombre="Giro a la derecha en la ascensión">
        <distanciaDesdeSalida unidad="km">146.1</distanciaDesdeSalida>
        <puntoGeografico>
            <longitud unidad="grados">-3.8100</longitud>
            <latitud unidad="grados">37.6300</latitud>
            <altitud unidad="m">1200</altitud>
        </puntoGeografico>
    </puntoAnónimo>
</puntosAnónimos>

<clasificaciónEtapa>
    <clasificado posición="1">
        <corredor>Marco Brenner</corredor>
        <nombreEquipo>Tudor Pro Cycling Team</nombreEquipo>
        <tiempo>04:15:09</tiempo>
        <diferencia>00:00:00</diferencia>
    </clasificado>
    <clasificado posición="2">
        <corredor>Santiago Buitrago</corredor>
        <nombreEquipo>Bahrain Victorious</nombreEquipo>
        <tiempo>04:15:10</tiempo>
        <diferencia>00:00:01</diferencia>
    </clasificado>
    <clasificado posición="3">
        <corredor>Cristián Rodríguez</corredor>
        <nombreEquipo>XDS Astana Team</nombreEquipo>
        <tiempo>04:15:20</tiempo>
        <diferencia>00:00:11</diferencia>
    </clasificado>
</clasificaciónEtapa>

<clasificaciónGeneral>
    <clasificado posición="1">
