=== SaPeLia/LaVuelta2026_SEW/xml/etapa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.uniovi.es" elementFormDefault="qualified"
	targetNamespace="http://www.uniovi.es" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="etapa">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="número" />
				<xs:element ref="longitud" />
				<xs:element ref="fecha" />
				<xs:element ref="tiempoGanador" />
				<xs:element ref="velocidadMedia" />
				<xs:element ref="desnivel" />
				<xs:element ref="ciudadSalida" />
				<xs:element ref="ciudadLlegada" />
				<xs:element ref="tipo" />
				<xs:element ref="referencias" />
				<xs:element ref="multimedia" />
				<xs:element ref="hitos" />
				<xs:element ref="puntosAnónimos" />
				<xs:element ref="clasificaciónEtapa" />
				<xs:element ref="clasificaciónGeneral" />
				<xs:element ref="clasificaciónEquipos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<xs:simpleType name="numeroEtapa">
		<xs:restriction base="xs:positiveInteger">
			<xs:minInclusive value="1" />
			<xs:maxInclusive value="21" />
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="número" type="numeroEtapa" />

	
	<xs:element name="longitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:decimal">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fecha" type="xs:date" />
	<xs:element name="tiempoGanador" type="xs:string" />
	<xs:element name="velocidadMedia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:decimal">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="desnivel">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="ciudadSalida">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="puntoGeografico" />
			</xs:sequence>
			<xs:attribute name="nombre" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="ciudadLlegada">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="puntoGeografico" />
			</xs:sequence>
			<xs:attribute name="nombre" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="puntoGeografico">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="tipoLatitud">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="-90" />
			<xs:maxInclusive value="90" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="tipoAltitud">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="0" />
			<xs:maxInclusive value="9000" />
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="latitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="tipoLatitud">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="altitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="tipoAltitud">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia">
		<xs:complexType>
			<xs:attribute name="título" type="xs:string" use="required" />
			<xs:attribute name="url" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="multimedia">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="fotografías" />
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="vídeos" />
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="audios" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotografías">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="fotografía" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotografía">
		<xs:complexType>
			<xs:attribute name="descripción" type="xs:string" use="required" />
			<xs:attribute name="archivo" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="vídeos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="vídeo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="vídeo">
		<xs:complexType>
			<xs:attribute name="descripción" type="xs:string" use="required" />
			<xs:attribute name="archivo" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="audios">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="audio" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="audio">
		<xs:complexType>
			<xs:attribute name="descripción" type="xs:string" use="required" />
			<xs:attribute name="archivo" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="hitos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="hito" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="hito">
		<xs:complexType>
			<xs:sequence>
				<xs:choice>
					<xs:element ref="puerto" />
					<xs:element ref="sprint" />
				</xs:choice>
				<xs:element ref="distanciaDesdeSalida" />
				<xs:element ref="puntoGeografico" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="puerto">
		<xs:complexType>
			<xs:attribute name="categoría" type="xs:string" use="required" />
			<xs:attribute name="nombre" type="xs:string" use="required" />
			<xs:attribute name="bonificado" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="si" />
						<xs:enumeration value="no" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="sprint">
		<xs:complexType>
			<xs:attribute name="tipo" type="xs:string" use="required" />
			<xs:attribute name="bonificado" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="si" />
						<xs:enumeration value="no" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="distanciaDesdeSalida">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="puntosAnónimos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="puntoAnónimo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="puntoAnónimo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="distanciaDesdeSalida" />
				<xs:element ref="puntoGeografico" />
			</xs:sequence>
			<xs:attribute name="nombre" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="clasificaciónEtapa">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="clasificado" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="clasificado">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="corredor" />
				<xs:element ref="equipo" />
				<xs:element ref="tiempo" />
				<xs:element ref="diferencia" />
			</xs:sequence>
			<xs:attribute name="posición" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="corredor" type="xs:string" />
	<xs:element name="equipo" type="xs:string" />
	<xs:element name="tiempo" type="xs:string" />
	<xs:element name="diferencia" type="xs:string" />
	<xs:element name="clasificaciónGeneral">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="clasificado" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="clasificaciónEquipos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="equipoClasificación" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="equipoClasificación">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="diferencia" />
			</xs:sequence>
			<xs:attribute name="posición" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== SaPeLia/LaVuelta2026_SEW/xml/etapaEsquema.xml
<etapa xmlns="http://www.uniovi.es" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.uniovi.es etapa.xsd">
    <nombre>Jaén a Sierra de la Pandera</nombre>
    <número>14</número>
    <longitud unidad="km">154.5</longitud>
    <fecha>2026-09-05</fecha>
    <tiempoGanador>04:15:09</tiempoGanador>
    <velocidadMedia unidad="km/h">22</velocidadMedia>
    <desnivel unidad="m">100</desnivel>
    <ciudadSalida nombre="Jaén">
        <puntoGeografico>
            <longitud unidad="grados">-3.7849</longitud>
            <latitud unidad="grados">37.7796</latitud>
            <altitud unidad="m">573</altitud>
        </puntoGeografico>
    </ciudadSalida>
    <ciudadLlegada nombre="Sierra de la Pandera">
        <puntoGeografico>
            <longitud unidad="grados">-3.8049</longitud>
            <latitud unidad="grados">37.6888</latitud>
            <altitud unidad="m">1830</altitud>
        </puntoGeografico>
    </ciudadLlegada>
    <tipo>montaña</tipo>
    <referencias>
        <referencia título="1" url="..." />
        <referencia título="2" url="..." />
        <referencia título="3" url="..." />
    </referencias>
    <multimedia>
        <fotografías>
            <fotografía descripción="foto1" archivo="../multimedia/foto1.jpg" />
            <fotografía descripción="foto2" archivo="../multimedia/foto2.jpg" />
            <fotografía descripción="foto3" archivo="../multimedia/foto3.jpg" />
        </fotografías>
        <vídeos>
            <vídeo descripción="vídeo1" archivo="../multimedia/vídeo1.mp4" />
        </vídeos>
        <audios>
            <audio descripción="audio1" archivo="../multimedia/audio1.mp3" />
        </audios>
    </multimedia>
    <hitos>
        <hito>
            <puerto nombre="Puerto de Los Villares" categoría="2ª Categoría" bonificado="no" />
            <distanciaDesdeSalida unidad="km">82.3</distanciaDesdeSalida>
            <puntoGeografico>
                <longitud unidad="grados">-3.8150</longitud>
                <latitud unidad="grados">37.6860</latitud>
                <altitud unidad="m">1250</altitud>
            </puntoGeografico>
        </hito>
        <hito>
            <sprint tipo="intermedio" bonificado="no" />
            <distanciaDesdeSalida unidad="km">123.6</distanciaDesdeSalida>
            <puntoGeografico>
                <longitud unidad="grados">-3.6440</longitud>
                <latitud unidad="grados">37.5790</latitud>
                <altitud unidad="m">950</altitud>
            </puntoGeografico>
        </hito>
        <hito>
            <puerto nombre="Puerto de Locubín" categoría="2ª Categoría" bonificado="no" />
            <distanciaDesdeSalida unidad="km">133.2</distanciaDesdeSalida>
            <puntoGeografico>
                <longitud unidad="grados">-3.8150</longitud>
                <latitud unidad="grados">37.5700</latitud>
                <altitud unidad="m">1200</altitud>
            </puntoGeografico>
        </hito>
        <hito>
            <puerto nombre="Sierra de la Pandera" categoría="1ª Categoría" bonificado="no" />
            <distanciaDesdeSalida unidad="km">154.5</distanciaDesdeSalida>
            <puntoGeografico>
                <longitud unidad="grados">-3.8049</longitud>
                <latitud unidad="grados">37.6888</latitud>
                <altitud unidad="m">1830</altitud>
            </puntoGeografico>
        </hito>
    </hitos>
    <puntosAnónimos>
        <puntoAnónimo nombre="Salida de Jaén">
            <distanciaDesdeSalida unidad="km">0.0</distanciaDesdeSalida>
            <puntoGeografico>
                <longitud unidad="grados">-3.7849</longitud>
                <latitud unidad="grados">37.7796</latitud>
                <altitud unidad="m">573</altitud>
            </puntoGeografico>
        </puntoAnónimo>
        <puntoAnónimo nombre="Rotonda dirección Mancha Real">
            <distanciaDesdeSalida unidad="km">3.4</distanciaDesdeSalida>
            <puntoGeografico>
                <longitud unidad="grados">-3.7800</longitud>
                <latitud unidad="grados">37.7900</latitud>
                <altitud unidad="m">580</altitud>
            </puntoGeografico>
        </puntoAnónimo>
        <puntoAnónimo nombre="Cruce dirección Mancha Real">
            <distanciaDesdeSalida unidad="km">9.1</distanciaDesdeSalida>
            <puntoGeografico>
                <longitud unidad="grados">-3.7700</longitud>
                <latitud unidad="grados">37.8000</latitud>
                <altitud unidad="m">610</altitud>
            </puntoGeografico>
        </puntoAnónimo>
        <puntoAnónimo nombre="Mancha Real">
            <distanciaDesdeSalida unidad="km">13.5</distanciaDesdeSalida>
            <puntoGeografico>
                <longitud unidad="grados">-3.6120</longitud>
                <latitud unidad="grados">37.7860</latitud>
                <altitud unidad="m">750</altitud>
            </puntoGeografico>
        </puntoAnónimo>
        <puntoAnónimo nombre="Cruce dirección Torres">
            <distanciaDesdeSalida unidad="km">24.6</distanciaDesdeSalida>
            <puntoGeografico>
                <longitud unidad="grados">-3.6500</longitud>
                <latitud unidad="grados">37.7500</latitud>
                <altitud unidad="m">850</altitud>
            </puntoGeografico>
        </puntoAnónimo>
        <puntoAnónimo nombre="Torres">
            <distanciaDesdeSalida unidad="km">33.1</distanciaDesdeSalida>
            <puntoGeografico>
                <longitud unidad="grados">-3.5100</longitud>
                <latitud unidad="grados">37.7850</latitud>
                <altitud unidad="m">880</altitud>
            </puntoGeografico>
        </puntoAnónimo>
        <puntoAnónimo nombre="Pegalajar">
            <distanciaDesdeSalida unidad="km">52.9</distanciaDesdeSalida>
            <puntoGeografico>
                <longitud unidad="grados">-3.6500</longitud>
                <latitud unidad="grados">37.7400</latitud>
                <altitud unidad="m">800</altitud>
            </puntoGeografico>
        </puntoAnónimo>
        <puntoAnónimo nombre="Rotonda dirección Jaén">
            <distanciaDesdeSalida unidad="km">57.9</distanciaDesdeSalida>
            <puntoGeografico>
                <longitud unidad="grados">-3.7200</longitud>
                <latitud unidad="grados">37.7500</latitud>
                <altitud unidad="m">700</altitud>
            </puntoGeografico>
        </puntoAnónimo>
        <puntoAnónimo nombre="La Guardia de Jaén">
            <distanciaDesdeSalida unidad="km">61.2</distanciaDesdeSalida>
            <puntoGeografico>
                <longitud unidad="grados">-3.6900</longitud>
                <latitud unidad="grados">37.7450</latitud>
                <altitud unidad="m">600</altitud>
            </puntoGeografico>
        </puntoAnónimo>
        <puntoAnónimo nombre="Puente Jontoya">
            <distanciaDesdeSalida unidad="km">67.2</distanciaDesdeSalida>
            <puntoGeografico>
                <longitud unidad="grados">-3.7700</longitud>
                <latitud unidad="grados">37.7350</latitud>
                <altitud unidad="m">550</altitud>
            </puntoGeografico>
        </puntoAnónimo>
        <puntoAnónimo nombre="Los Villares">
            <distanciaDesdeSalida unidad="km">82.3</distanciaDesdeSalida>
            <puntoGeografico>
                <longitud unidad="grados">-3.8150</longitud>
                <latitud unidad="grados">37.6860</latitud>
                <altitud unidad="m">980</altitud>
            </puntoGeografico>
        </puntoAnónimo>
        <puntoAnónimo nombre="Fuensanta de Martos">
            <distanciaDesdeSalida unidad="km">101.2</distanciaDesdeSalida>
            <puntoGeografico>
                <longitud unidad="grados">-3.9050</longitud>
                <latitud unidad="grados">37.6470</latitud>
                <altitud unidad="m">720</altitud>
            </puntoGeografico>
        </puntoAnónimo>
        <puntoAnónimo nombre="El Regüelo">
            <distanciaDesdeSalida unidad="km">109.3</distanciaDesdeSalida>
            <puntoGeografico>
                <longitud unidad="grados">-3.8900</longitud>
                <latitud unidad="grados">37.6100</latitud>
                <altitud unidad="m">800</altitud>
            </puntoGeografico>
        </puntoAnónimo>
        <puntoAnónimo nombre="Castillo de Locubín">
            <distanciaDesdeSalida unidad="km">123.1</distanciaDesdeSalida>
            <puntoGeografico>
                <longitud unidad="grados">-3.9430</longitud>
                <latitud unidad="grados">37.5280</latitud>
                <altitud unidad="m">700</altitud>
            </puntoGeografico>
        </puntoAnónimo>
        <puntoAnónimo nombre="Comienzo del puerto final">
            <distanciaDesdeSalida unidad="km">124.4</distanciaDesdeSalida>
            <puntoGeografico>
                <longitud unidad="grados">-3.9000</longitud>
                <latitud unidad="grados">37.5600</latitud>
                <altitud unidad="m">850</altitud>
            </puntoGeografico>
        </puntoAnónimo>
        <puntoAnónimo nombre="Valdepeñas de Jaén">
            <distanciaDesdeSalida unidad="km">139.5</distanciaDesdeSalida>
            <puntoGeografico>
                <longitud unidad="grados">-3.8150</longitud>
                <latitud unidad="grados">37.5870</latitud>
                <altitud unidad="m">920</altitud>
            </puntoGeografico>
        </puntoAnónimo>
        <puntoAnónimo nombre="Giro a la derecha en la ascensión">
            <distanciaDesdeSalida unidad="km">146.1</distanciaDesdeSalida>
            <puntoGeografico>
                <longitud unidad="grados">-3.8100</longitud>
                <latitud unidad="grados">37.6300</latitud>
                <altitud unidad="m">1200</altitud>
            </puntoGeografico>
        </puntoAnónimo>
    </puntosAnónimos>
    <clasificaciónEtapa>
